#pragma once

/**
 * copying from <X11/corsorfont.h>
 */

#define NFC_X_cursor 0
#define NFC_arrow 2
#define NFC_based_arrow_down 4
#define NFC_based_arrow_up 6
#define NFC_boat 8
#define NFC_bogosity 10
#define NFC_bottom_left_corner 12
#define NFC_bottom_right_corner 14
#define NFC_bottom_side 16
#define NFC_bottom_tee 18
#define NFC_box_spiral 20
#define NFC_center_ptr 22
#define NFC_circle 24
#define NFC_clock 26
#define NFC_coffee_mug 28
#define NFC_cross 30
#define NFC_cross_reverse 32
#define NFC_crosshair 34
#define NFC_diamond_cross 36
#define NFC_dot 38
#define NFC_dotbox 40
#define NFC_double_arrow 42
#define NFC_draft_large 44
#define NFC_draft_small 46
#define NFC_draped_box 48
#define NFC_exchange 50
#define NFC_fleur 52
#define NFC_gobbler 54
#define NFC_gumby 56
#define NFC_hand1 58
#define NFC_hand2 60
#define NFC_heart 62
#define NFC_icon 64
#define NFC_iron_cross 66
#define NFC_left_ptr 68
#define NFC_left_side 70
#define NFC_left_tee 72
#define NFC_leftbutton 74
#define NFC_ll_angle 76
#define NFC_lr_angle 78
#define NFC_man 80
#define NFC_middlebutton 82
#define NFC_mouse 84
#define NFC_pencil 86
#define NFC_pirate 88
#define NFC_plus 90
#define NFC_question_arrow 92
#define NFC_right_ptr 94
#define NFC_right_side 96
#define NFC_right_tee 98
#define NFC_rightbutton 100
#define NFC_rtl_logo 102
#define NFC_sailboat 104
#define NFC_sb_down_arrow 106
#define NFC_sb_h_double_arrow 108
#define NFC_sb_left_arrow 110
#define NFC_sb_right_arrow 112
#define NFC_sb_up_arrow 114
#define NFC_sb_v_double_arrow 116
#define NFC_shuttle 118
#define NFC_sizing 120
#define NFC_spider 122
#define NFC_spraycan 124
#define NFC_star 126
#define NFC_target 128
#define NFC_tcross 130
#define NFC_top_left_arrow 132
#define NFC_top_left_corner 134
#define NFC_top_right_corner 136
#define NFC_top_side 138
#define NFC_top_tee 140
#define NFC_trek 142
#define NFC_ul_angle 144
#define NFC_umbrella 146
#define NFC_ur_angle 148
#define NFC_watch 150
#define NFC_xterm 152
#define NFC_num_glyphs 154