#pragma once

#include <xcb/xcb.h>

#define WINDOW_MANAGER_STRUCTURE_MASK \
  XCB_EVENT_MASK_STRUCTURE_NOTIFY | XCB_EVENT_MASK_SUBSTRUCTURE_NOTIFY | XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT | XCB_EVENT_MASK_PROPERTY_CHANGE
/**
 * Mask for window manager/root window property
 * XCB_EVENT_MASK_KEY_PRESS | XCB_EVENT_MASK_KEY_RELEASE |
 */
#define WINDOW_MANAGER_MASK \
  WINDOW_MANAGER_STRUCTURE_MASK | XCB_EVENT_MASK_BUTTON_PRESS | XCB_EVENT_MASK_POINTER_MOTION | XCB_EVENT_MASK_KEY_PRESS | XCB_EVENT_MASK_ENTER_WINDOW | XCB_EVENT_MASK_LEAVE_WINDOW | XCB_EVENT_MASK_PROPERTY_CHANGE

/**
 * Mask for move window [X, Y]
 */
#define WIN_MOVE_MASK \
  XCB_CONFIG_WINDOW_X | XCB_CONFIG_WINDOW_Y

/**
 * Mask for resize window [W, H]
 */
#define WIN_RESIZE_MASK \
  XCB_CONFIG_WINDOW_WIDTH | XCB_CONFIG_WINDOW_HEIGHT

/**
 * Mask for both move and resize window [X, Y, W, H]
 */
#define WIN_MOVE_RESIZE_MASK \
  WIN_MOVE_MASK | WIN_RESIZE_MASK
